### ISSUE TITLE
Demo SSL certificate expired

### ISSUE THREAD

**Issue by simenbrekken** [mariusGundersen/module-pusher#1]
Seems the certificate used for the demo has expired.

![image](https://cloud.githubusercontent.com/assets/12807/19112723/b938ec3e-8b06-11e6-9ff3-40fe0adf1de6.png)

**Comment by mariusGundersen** [comment]
Thanks for the heads up, I must have forgotten this server when I updated
the certificates. I'll try to fix it soon.

Marius Gundersen

**Comment by mariusGundersen** [comment]
Fixed
